# Generated by Django 4.2.16 on 2025-01-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_alter_queue_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Была создана'),
        ),
    ]
