# Generated by Django 4.2.16 on 2025-01-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0003_queue_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Была создана'),
        ),
    ]
