# Generated by Django 4.2.16 on 2025-02-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0004_alter_queue_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'verbose_name': 'Очередь', 'verbose_name_plural': 'Очереди'},
        ),
        migrations.AlterModelOptions(
            name='queuejoin',
            options={'verbose_name': 'Присоединение к очереди', 'verbose_name_plural': 'Присоединения к очередям'},
        ),
        migrations.AlterField(
            model_name='queuejoin',
            name='position',
            field=models.IntegerField(verbose_name='Позиция в очереди'),
        ),
    ]
