# Generated by Django 4.2.16 on 2025-02-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('email', models.EmailField(max_length=150, verbose_name='Электронная почта')),
                ('message', models.TextField(max_length=2000, verbose_name='Сообщение')),
            ],
        ),
    ]
