"""Delete slug  from Queue model

Revision ID: 47f909c8b46c
Revises: 6c96ac9b70a5
Create Date: 2024-08-26 17:44:48.547353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f909c8b46c'
down_revision = '6c96ac9b70a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
